inherit_from: .rubocop_todo.yml

require: 
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: '2.6.6'
  Include:
    - 'app/**/*'
    - 'spec/**/*'
  Exclude:
    - 'spec/**/*.yml'
    - 'app/views/**/*'
    - 'app/assets/**/*'
    - 'app/javascript/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
  Include: 
    - 'app/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: true
  Include:
    - 'app/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
